<a href="https://colab.research.google.com/github/ThomasSpare/Learning_Pytorch_1/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LISTS**













In [6]:
import torch
import numpy as np


In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.21459332, 0.94790894, 0.80355563, 0.32570896],
       [0.58748439, 0.90365016, 0.99099841, 0.57981278],
       [0.50374273, 0.31476234, 0.66059474, 0.57368026]])

In [8]:
np1.dtype

dtype('float64')

# **TENSOR**

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.4804, -1.1218,  1.1877, -0.4634],
        [ 0.2921,  1.2092, -2.5741,  0.4086],
        [ 1.8302, -1.1726,  0.7576, -0.3740]])

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2146, 0.9479, 0.8036, 0.3257],
        [0.5875, 0.9037, 0.9910, 0.5798],
        [0.5037, 0.3148, 0.6606, 0.5737]], dtype=torch.float64)